"""empty message

Revision ID: 89caca40187b
Revises: 
Create Date: 2020-07-13 01:39:58.531015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89caca40187b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_url',
    sa.Column('alias', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_index(op.f('ix_short_url_alias'), 'short_url', ['alias'], unique=False)
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('alias', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['alias'], ['short_url.alias'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4'
    )
    op.create_index(op.f('ix_statistic_alias'), 'statistic', ['alias'], unique=False)
    op.create_index(op.f('ix_statistic_date'), 'statistic', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistic_date'), table_name='statistic')
    op.drop_index(op.f('ix_statistic_alias'), table_name='statistic')
    op.drop_table('statistic')
    op.drop_index(op.f('ix_short_url_alias'), table_name='short_url')
    op.drop_table('short_url')
    # ### end Alembic commands ###
